name: Packer
on:
  push:
      paths:
        - '*.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: packer validate ubuntu1804.json
        uses: docker://jetbrainsinfra/packer:1.3.4-vsphere-2.3-teamcity-1.0
        with:
          args: validate ubuntu1804.json
      - name: packer build ubuntu1804.json
        uses: docker://jetbrainsinfra/packer:1.3.4-vsphere-2.3-teamcity-1.0
        with:
          args: build ubuntu1804.json
        env:
          VSPHERE_USER: ${{ secrets.VSPHERE_USER }}
          VSPHERE_PASSWORD: ${{ secrets.VSPHERE_PASSWORD }}
          VSPHERE_URL: ${{ secrets.VSPHERE_URL }}
          ESX_HOST: ${{ secrets.ESX_HOST }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
